### get all todolist
GET http://localhost:8080/api/todolist
Accept: application/json

### get todolsit by id
GET http://localhost:8080/api/todolist/2
Accept: application/json

### delete todolist by id
DELETE http://localhost:8080/api/todolist/6
Accept: application/json

### create todolist
POST http://localhost:8080/api/todolist
Accept: application/json
Content-Type: application/json

{
  "title": "wake",
  "description": "wake at home"
}

### update todolist
PUT http://localhost:8080/api/todolist/2
Accept: application/json
Content-Type: application/json

{
  "title": "workout",
  "description": "workout at home",
  "isDone": true
}

### create new user
POST http://localhost:8080/auth/register
Accept: application/json
Content-Type: application/json

{
  "name": "arief",
  "email": "arief@mail.com",
  "password": "123"
}

### login user
POST http://localhost:8080/auth/login
Accept: application/json
Content-Type: application/json

{
  "email": "arief@mail.com",
  "password": "123"
}